# TRABALHO DE IAA017 – Introdução à Ciência de Dados

Baixar bibliotecas:
```pip install pandas seaborn matplotlib openpyxl```

---

### Import das bibliotecas

In [8]:
# Biblioteca Pandas - Manipulação de dados
import pandas as pd
# Biblioteca Seaborn - Criação de gráficos
import seaborn as sns
# Biblioteca Matplotlib - Criação de gráficos
import matplotlib.pyplot as plt

# Biblioteca para ignorar mensagens de warning (aviso) ao rodar uma célula de código
import warnings
warnings.filterwarnings('ignore')

## Analise exploratoria dos dados

In [12]:
# Lendo arquivo Excel
dados = pd.read_excel('Dados_Sneakers_World3.xlsx', sheet_name=None)

In [ ]:
# Validando as chaves do dicionário 'dados' para verificar os nomes das planilhas
dados.keys()

dict_keys(['Sales', 'ProdCategory', 'ProdSubcategory', 'Produt', 'Region', 'Seller'])

In [ ]:
# Verificando se existem valores nulos na coluna 'Sales' da planilha 'Sales'
dados['Sales'].isna().any()

OrderNumber         False
ProductID           False
ResellerKey         False
EmployeeID          False
SalesTerritoryID    False
Quantity            False
UnitPrice           False
Sales               False
Cost                False
OrderDate           False
ShipDate            False
DeliveryDate        False
dtype: bool

In [ ]:
# Verificando se existem valores nulos na coluna 'ProdCategory' da planilha 'Products'
dados['ProdCategory'].isna().any()

CategoryID    False
Category      False
dtype: bool

In [ ]:
# Verificando se existem valores nulos na coluna 'ProdSubcategory' da planilha 'Products'
dados['ProdSubcategory'].isna().any()

SubcategoryID    False
Subcategory      False
CategoryID       False
dtype: bool

In [ ]:
# Verificando se existem valores nulos na coluna 'ProdID' da planilha 'Products'
dados['Produt'].isna().any()

ProductID        False
Product          False
ExtraCost        False
Color            False
CategoryID       False
SubcategoryID    False
dtype: bool

In [ ]:
# Verificando se existem valores nulos na coluna 'Region' da planilha 'Sales'
dados['Region'].isna().any()

SalesTerritoryID    False
Region              False
Country             False
Continent           False
dtype: bool

In [ ]:
# Verificando se existem valores nulos na coluna 'Country' da planilha 'Sales'
dados['Seller'].isna().any()

EmployeeID          False
Seller              False
Title               False
UPN                 False
SalesTerritoryID    False
dtype: bool

In [ ]:
# Verificando se existem valores duplicados na coluna 'Sales' da planilha 'Sales'
dados['Sales'].duplicated().sum()

np.int64(0)

In [ ]:
# Verificando se existem valores duplicados na coluna 'ProdCategory' da planilha 'Products'
dados['ProdCategory'].duplicated().sum()

np.int64(0)

In [ ]:
# Verificando se existem valores duplicados na coluna 'ProdSubcategory' da planilha 'Products'
dados['ProdSubcategory'].duplicated().sum()

np.int64(0)

In [ ]:
# Verificando se existem valores duplicados na coluna 'ProdID' da planilha 'Products'
dados['Produt'].duplicated().sum()

np.int64(0)

In [ ]:
# Verificando se existem valores duplicados na coluna 'Region' da planilha 'Sales'
dados['Region'].duplicated().sum()

np.int64(0)

In [ ]:
# Verificando se existem valores duplicados na coluna 'Seller' da planilha 'Sales'
dados['Seller'].duplicated().sum()

np.int64(0)

In [ ]:
# Exibindo as primeiras linhas da coluna 'Sales' da planilha 'Sales'
dados['Sales'].head()

,OrderNumber,ProductID,ResellerKey,EmployeeID,SalesTerritoryID,Quantity,UnitPrice,Sales,Cost,OrderDate,ShipDate,DeliveryDate
0,PV5417,17,674,141,1,2,11.019,22.038,18.719550,2023-02-18,2023-02-23,2023-03-15
1,PV7604,17,674,141,1,3,11.019,33.057,23.563031,2023-05-20,2023-05-30,2023-06-17
2,PV3568,17,638,141,1,1,11.019,11.019,9.582128,2022-11-27,2022-12-03,2022-12-14
3,PV1699,17,498,141,1,1,11.019,11.019,9.428274,2022-09-16,2022-09-17,2022-10-04
4,PV4003,17,498,141,1,10,11.019,110.190,98.119612,2022-12-16,2022-12-24,2023-01-03

In [ ]:
# Exibindo as últimas linhas da coluna 'Sales' da planilha 'Sales'
dados['Sales'].dtypes

OrderNumber                    str
ProductID                    int64
ResellerKey                  int64
EmployeeID                   int64
SalesTerritoryID             int64
Quantity                     int64
UnitPrice                  float64
Sales                      float64
Cost                       float64
OrderDate           datetime64[us]
ShipDate            datetime64[us]
DeliveryDate        datetime64[us]
dtype: object

In [ ]:
# Exibindo as primeiras linhas da coluna 'ProdCategory' da planilha 'Products'
dados['ProdCategory'].head()

   CategoryID           Category
0           1     Speed Sneakers
1           2  Training Sneakers
2           3    Enduro Sneakers
3           4       Gyn Sneakers

In [ ]:
# Exibindo as últimas linhas da coluna 'ProdCategory' da planilha 'Products'
dados['ProdCategory'].dtypes

CategoryID    int64
Category        str
dtype: object

In [ ]:
# Exibindo as primeiras linhas da coluna 'ProdSubcategory' da planilha 'Products'
dados['ProdSubcategory'].head()

   SubcategoryID    Subcategory  CategoryID
0             36  Cross Country           3
1              5       Mountain           3
2              4       Off Road           3
3              7           Flex           4
4             21     Flex Light           4

In [ ]:
# Exibindo as últimas linhas da coluna 'ProdSubcategory' da planilha 'Products'
dados['ProdSubcategory'].dtypes

SubcategoryID    int64
Subcategory        str
CategoryID       int64
dtype: object

In [ ]:
# Exibindo as primeiras linhas da coluna 'ProdID' da planilha 'Products'
dados['Produt'].head()

,ProductID,Product,ExtraCost,Color,CategoryID,SubcategoryID
0,5,"Mountain-1 Silver, 42",1912.15,Silver,3,5
1,6,"Cat's Sports, 36",24.75,Black,4,7
2,15,"Prime Jaguar - Black, 34",868.63,Black,1,1
3,16,"Prime Jaguar - Red, 34",868.63,Red,1,1
4,17,"Sport-1 Tiger, Red, 38",12.03,Red,2,2

In [ ]:
# Exibindo as últimas linhas da coluna 'ProdID' da planilha 'Products'
dados['Produt'].dtypes

ProductID          int64
Product              str
ExtraCost        float64
Color                str
CategoryID         int64
SubcategoryID      int64
dtype: object

In [ ]:
# Exibindo as primeiras linhas da coluna 'Region' da planilha 'Sales'
dados['Region'].head()

   SalesTerritoryID        Region Country       Continent
0                 1      Nordeste  Brasil  América Latina
1                 2         Norte  Brasil  América Latina
2                 3           Sul  Brasil  América Latina
3                 4       Sudeste  Brasil  América Latina
4                 5  Centro-Oeste  Brasil  América Latina

In [ ]:
# Exibindo as últimas linhas da coluna 'Region' da planilha 'Sales'
dados['Region'].dtypes

SalesTerritoryID    int64
Region                str
Country               str
Continent             str
dtype: object

In [ ]:
# Exibindo as primeiras linhas da coluna 'Seller' da planilha 'Sales'
dados['Seller'].head()

,EmployeeID,Seller,Title,UPN,SalesTerritoryID
0,141,Artur Borges,Vendedor,artur@sneakersworld.com,1
1,143,Claudia Pereira,Vendedor,claudia@sneakersworld.com,2
2,145,Luiza Ramos,Vendedor,luiza@sneakersworld.com,3
3,147,Mohammed El Fassi,Vendedor,mohammed@sneakersworld.com,4
4,148,Abebe Bekele,Vendedor,abebe@sneakersworld.com,5

In [ ]:
# Exibindo as últimas linhas da coluna 'Seller' da planilha 'Sales'
dados['Seller'].dtypes

EmployeeID          int64
Seller                str
Title                 str
UPN                   str
SalesTerritoryID    int64
dtype: object

### Validando dados

In [42]:
# Criando categorias para separar numéricas e categóricas
numericas_cols = [col for col in dados['Sales'].columns if dados['Sales'][col].dtype != 'str']
categoricas_cols = [col for col in dados['Sales'].columns if dados['Sales'][col].dtype == 'str']

In [ ]:
# Exibindo as estatísticas descritivas para as colunas numéricas da planilha 'Sales'
dados['Sales'][numericas_cols].describe()

,ProductID,ResellerKey,EmployeeID,SalesTerritoryID,Quantity,UnitPrice,Sales,Cost,OrderDate,ShipDate,DeliveryDate
count,57780.000000,57780.000000,57780.000000,57780.000000,57780.000000,57780.000000,57780.000000,57780.000000,57780,57780,57780
mean,214.045517,545.435981,147.647525,4.555088,3.529076,53.761489,166.137680,132.985357,2024-04-16 07:18:15.327102,2024-04-24 08:29:27.476635,2024-05-04 20:21:09.532710
min,17.000000,206.000000,141.000000,1.000000,1.000000,9.133000,9.137000,6.447017,2022-07-01 00:00:00,2022-07-03 00:00:00,2022-07-09 00:00:00
25%,131.000000,371.000000,145.000000,3.000000,2.000000,12.500000,42.482500,34.038387,2023-09-18 00:00:00,2023-09-27 00:00:00,2023-10-07 00:00:00
50%,207.000000,532.000000,147.000000,4.000000,3.000000,30.845000,85.671000,68.169068,2024-06-07 00:00:00,2024-06-17 00:00:00,2024-06-27 00:00:00
75%,296.000000,719.000000,150.000000,6.000000,4.000000,76.229000,192.958000,152.731281,2024-11-17 00:00:00,2024-11-24 00:00:00,2024-12-05 00:00:00
max,411.000000,906.000000,158.000000,10.000000,44.000000,295.601000,3333.304000,2633.457502,2025-05-31 00:00:00,2025-06-15 00:00:00,2025-07-04 00:00:00
std,113.530608,205.420978,4.472951,2.412933,3.037049,52.427990,223.636706,179.902410,NaN,NaN,NaN

In [ ]:
# Exibindo as estatísticas descritivas para as colunas categóricas da planilha 'Sales'
dados['Sales'][categoricas_cols].describe()

       OrderNumber
count        57780
unique       57747
top        PV28287
freq             2

---
## 2. Visualização dos dados